### ISSUE TITLE
Duplicated controller instances

### ISSUE THREAD

**Issue by zmitic** [symfony/stimulus-bridge#27]
I am using latest bridge and even default ``hello_controller.js`` can be used to replicate bug.

For HTML like this:

```twig
    <div data-controller="hello" data-hello-name="1"></div>
    <div data-controller="hello" data-hello-name="2"></div>
```

and ``hello_controller.js`` like this:

```js
import { Controller } from 'stimulus';

/* stimulusFetch: 'lazy' */
export default class extends Controller {
    static targets = [ "name" ];

    connect() {
        console.log(this.element.getAttribute('data-hello-name'));
    }
}
```

each block is instantiated twice:

![image](https://user-images.githubusercontent.com/1964158/107129385-65298d00-68c5-11eb-8b0b-63b80103da70.png)

---

If I add third:

```twig
    <div data-controller="hello" data-hello-name="1"></div>
    <div data-controller="hello" data-hello-name="2"></div>
    <div data-controller="hello" data-hello-name="3"></div>
```

each is loaded 3 times:

![image](https://user-images.githubusercontent.com/1964158/107129404-838f8880-68c5-11eb-9275-00b389fa50f3.png)

---

Problem is gone if I remove ``/* stimulusFetch: 'lazy' */`` or there is only 1 controller.

I followed all the steps from [upgrade docs](https://symfony.com/blog/webpack-encore-1-0-and-stimulus-bridge-2-0-released) to make sure I don't mess anything (I am noob when it comes to JS).

**Comment by weaverryan** [comment]
Hey @zmitic!

Thanks for the very detailed report! This looks legit - it looks like we're missing some tracking to not re-register the lazy controllers. I'm checking into it right now :).

Cheers!

**Comment by weaverryan** [comment]
Fixed in #28!

**Comment by zmitic** [comment]
Thank you, that was super fast. Will you tag it or do I use dev-master?

**Comment by weaverryan** [comment]
We will tag it tomorrow (Sunday) :)
