### ISSUE TITLE
 Your controllers.json file was not found

### ISSUE THREAD

**Issue by Dannebicque** [symfony/stimulus-bridge#30]
Hello,

I used Symfony/ux-chartjs, for a few weeks, no problem.
Today I updated my package.json, especially by switching to the latest version of webpack/again (1.0.5), Stymulus (2), and it no longer works :(

I have this error, when I run "yarn encore dev" 
Syntax Error: Error: Your controllers.json file was not found. Be sure to add a Webpack alias from "@symfony/stimulus-bridge/controllers.json" to *your* controllers.json file.

But, I have my controllers.json in assets/

```js
{
  "controllers": {
    "@symfony/ux-chartjs": {
      "chart": {
        "enabled": true,
        "fetch": "eager",
        "webpackMode": "eager"
      }
    }
  },
  "entrypoints": []
}
```

And in Webpack 
```js
.enableStimulusBridge(
    './assets/controllers.json'
  )
```

I think i have the good configuration ?

Thanks for your help
David

**Comment by tgalopin** [comment]
Hi! Did you update the stimulus-bridge to 2.0 as well?

**Comment by Dannebicque** [comment]
Yes, everything was up to date. 
I just also relaunched the recipe update on webpack again. And now it seems to be working. I hadn't created the bootstrap file.js, and left the code (to retrieve the controllers) in app.js (in a js directory).

I have other problems with Encore, but more with Symfony/UX. Thanks for the quick response.

**Comment by Dannebicque** [comment]
Hello,

I try, again to reinstall all the package, but always the same error. I use Webpack 5, maybe it is the problem ?
If I comment the line in se Symfony/stimulus-bridge which show the message, 

```js
  // if ('undefined' !== typeof config['placeholder']) {
  //   throw new Error('Your controllers.json file was not found. Be sure to add a Webpack alias from "@symfony/stimulus-bridge/controllers.json" to *your* controllers.json file.');
  // }
  //
  // if ('undefined' === typeof config['controllers']) {
  //   throw new Error('Your Stimulus configuration file (assets/controllers.json) lacks a "controllers" key.');
  // }
```

the compilation works, necessarily, but I have no charts in my page :( 
I really do not understand the message, because I have the file, and if I test the condition, I have "true" as an answer for config['placeholder'], because it takes the value of the initial controllers.json in the package ? not mine?

If I put my controllers.json directly inside the nodes_modules (to test...) All works fine. I don't know if theses informations can help...

Thanks.

**Comment by mdriessen** [comment]
Hi! I've had the same problem and compared your config with mine. It turns out the alias is overwritten by setting it with config.resolve.alias = {....}. Instead you need to call Encore.addAliases({}) for adding your parchment and quill alias instead of overwriting the array.

**Comment by tgalopin** [comment]
Ah indeed, the bridge now uses an alias that you shouldn't override (I didn't notice it in your config initially).

**Comment by Dannebicque** [comment]
Hi @mdriessen et @tgalopin 

Many thanks, it works fine now ! I would never have found this mistake. Many thanks !!

I Close this issue.
