### ISSUE TITLE
SECURITY - control the output CSS & JS file names

### ISSUE THREAD

**Issue by benr77** [symfony/stimulus-bridge#31]
I notice that the output filenames inserted in to the HTML document are quite verbose, and also give away the use of Symfony in the backend, which in my opinion is not a particularly good thing.

For example, I'm using the Charts UX package and see this in my HTML document

`/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_symfony_ux-chartjs_di-35626c.css`

Is it possible to change the name of this output file - mainly to remove the Symfony / Stimulus Bridge identifiers? 

Any thoughts?

Thank you.

**Comment by tgalopin** [comment]
These names are only there in development and they are provided by Webpack 5 to help understand which files are compiled. You should be fine when running the prod build.

**Comment by benr77** [comment]
Good point - I'd forgotten about the prod build output being different. My bad.

Thanks for the clarification.
