### ISSUE TITLE
Typescript typings are not found

### ISSUE THREAD

**Issue by tjveldhuizen** [symfony/stimulus-bridge#39]
Inspired by the SymfonyCasts series on Stimulus, I've started using it in my project. However, I'ld like to use Typescript. I can't get the `@symfony/stimulus-bridge-types` package to work. Since it's not in the @types -namespace, it's not automatically detected. Therefore I've adapted my typeRoots-property in tsconfig.json, but it's still not detected:
```{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "typeRoots": [
      "node_modules/@types",
      "node_modules/@symfony/stimulus-bridge-types"
    ]
  }
}
```

Is there a specific reason to put the index.d.ts in a separate package? Since it's so small, I think it can be bundled in the main package (https://www.typescriptlang.org/docs/handbook/2/type-declarations.html#external-definitions)

**Comment by cfoehrdes** [comment]
I can't find any information on how to get this `@symfony/stimulus-bridge-types` to work. Also tried the typeRoots etc.

**Comment by cfoehrdes** [comment]
I found out how to load the stimulus bridge types by the explanation in [this issue comment](https://github.com/microsoft/TypeScript/issues/22217#issuecomment-369783776).

```
"compilerOptions": {
        "target": "esnext",
        "moduleResolution": "node",
        "allowJs": true,
        "noEmit": true,
        "strict": true,
        "isolatedModules": true,
        "esModuleInterop": true,
        "baseUrl": "./",
        "paths": {
            "*": [
                "node_modules/@symfony/stimulus-bridge-types"
            ]
        }
    },
```

You have to add the package to the `paths` instead of `typeRoots`.

**Comment by criszz77** [comment]
I don't know why, but this is how I managed to make typeRoots work:
![image](https://user-images.githubusercontent.com/55203625/141511681-a3d486d7-1cfb-41bd-952d-394c9f24496d.png)

**Comment by Nek-** [comment]
I use this configuration otherwise I have problems with bootstrap types:

```javascript
{
    "compilerOptions": {
        "outDir": "./dist/",
        "noImplicitAny": true,
        "module": "es6",
        "target": "es5",
        "jsx": "react",
        "allowJs": true,
        "moduleResolution": "node",
        "baseUrl": "./",
        "paths": {
            "@symfony/stimulus-bridge": [
                "node_modules/@symfony/stimulus-bridge-types"
            ]
        }
    }
}

```

**Comment by weaverryan** [comment]
See #55 :)
