### ISSUE TITLE
Controllers in subfolders not detected

### ISSUE THREAD

**Issue by pcarballeda** [symfony/stimulus-bridge#41]
Hello, good morning. I am experiencing problems with Stimulus controllers and namespaces.

When I use my controllers like this everything works as expected:
`/controllers/gifts_controller.js`
`data-controller="gifts"`

![image](https://user-images.githubusercontent.com/4659020/116232678-be81b980-a75a-11eb-9dcb-1e08f2ebbbce.png)

If I use the controllers this way, nothing works:
`/controllers/frontend/gifts_controller.js`
`data-controller="frontend--gifts_controller.js"`

![image](https://user-images.githubusercontent.com/4659020/116232625-af9b0700-a75a-11eb-8cca-70c656d48803.png)

[Stimulus documentation](https://stimulus.hotwire.dev/handbook/installing#controller-filenames-map-to-identifiers) specifies that the name convention for controllers in subfolders must be like the second example, but it don't work. 

I am not sure if I am doing anything wrong or if this feature is not available but I can't make it work.

**Comment by tgalopin** [comment]
Hi! Would you paste here the content of your bootstrap.js file? Are you using the default setup coming with Webpack Encore?

**Comment by Kocal** [comment]
Hi!
I'm also using controllers in subfolders, but everything works fine when using the default [bootstrap.js](https://github.com/symfony/recipes/blob/master/symfony/webpack-encore-bundle/1.0/assets/bootstrap.js) from the Symfony recipes for Webpack Encore Bundle.

Are you calling `startStimulusApp(require.context(...))` with the good parameters somewhere?

**Comment by pcarballeda** [comment]
I am using the default setup, I have not modified bootstrap.js or anything else.

**Comment by tgalopin** [comment]
I'd still be interested in seeing your bootstrap.js file if you can share it. Thanks!

**Comment by pcarballeda** [comment]
Sorry about the delay, here is my bootstrap.js. I am closing the issue since it is working now. I don't know what was wrong but is working properly since I deleted `node_modules` and reinstalled everything.

```
import { startStimulusApp } from '@symfony/stimulus-bridge';

// Registers Stimulus controllers from controllers.json and in the controllers/ directory
export const app = startStimulusApp(require.context(
    '@symfony/stimulus-bridge/lazy-controller-loader!./controllers',
    true,
    /\.(j|t)sx?$/,
));
```
