### ISSUE TITLE
stimulus-bridge loader.js

### ISSUE THREAD

**Issue by popoi90** [symfony/stimulus-bridge#62]
When I run yarn watch... build fails with this error.

Module build failed (from ./node_modules/@symfony/stimulus-bridge/dist/webpack/loader.js):
Error: Could not retrieve module factory for type LoaderDependency

I have...
"@symfony/stimulus-bridge": "^3.0.0",
 "@symfony/webpack-encore": "^1.7.0"
"@hotwired/stimulus": "^3.0.1",
webpack 5.65
node 14.7..

Thanks in advance

**Comment by weaverryan** [comment]
Hey!

That `loader.js` file is looking specifically for a file that should live here inside your app: `node_modules/webpack/lib/dependencies/LoaderDependency.js`.

Does that file exist for you? It does for me - I'm using Webpack 5.65.0 also.
