### ISSUE TITLE
Lazy controllers connect twice

### ISSUE THREAD

**Issue by jmsche** [symfony/stimulus-bridge#67]
Hi there,

I noticed a strange thing in my browser console yesterday:

![image](https://user-images.githubusercontent.com/3929498/169967001-9b954c66-b327-40fb-b45a-739ab12cbae2.png)

After a little debugging, I found out that the culprit seems to be... configuring the controller as lazy using this code just above the controller class:

```js
/* stimulusFetch: 'lazy' */
```

Tell me if there's more information I can provide to debug this.

**Comment by jmsche** [comment]
It seems the issue also exists when configuring Symfony UX controllers as lazy as well.

**Comment by weaverryan** [comment]
This is not something I realized would happen, but it's expected. See #67.

To get lazy controllers to work, we register a "fake" controller under your controller's name. Inside `initialize()`, that "fake" controller loads your REAL controller and registers it with Stimulus. So, the first initialize/connect that you see is for the "fake" controller. Then, immediately, your real controller replaces the "fake" one. The `disconnect()` that you see is the fake controller disconnecting.

So, this adds some unfortunate noise, but it's nothing to worry about. If you have code inside your controller's `initialize()` or `connect()` methods, it is only executed ONCE as expected.

Cheers!
