### ISSUE TITLE
VueJS - Could not retrieve module factory for type LoaderDependency

### ISSUE THREAD

**Issue by jmariller** [symfony/stimulus-bridge#71]
Hi,

I am trying to use Stimulus with VueJS, unfortunately I always get the same error message during compilation:
> Could not retrieve module factory for type LoaderDependency

Here is an extract of `package.json`:
![image](https://user-images.githubusercontent.com/48550159/172856535-0767ab03-6e02-47c8-b9c1-aa3919a70ef8.png)

`webpack.config.js`:
![image](https://user-images.githubusercontent.com/48550159/172856662-d08de3da-19e3-4237-99d2-b9be94d97469.png)

And the full error message:
![image](https://user-images.githubusercontent.com/48550159/172857077-cb868d20-4d7a-4729-b09c-90b9feb891f0.png)

I suspect this has to do with the different versions of Webpack - I tried to remove the dependencies from `package.json`, but then got this error message:
![image](https://user-images.githubusercontent.com/48550159/172857294-4f8f31b4-b56c-43f5-aef2-aff1ee9236ae.png)

Does anybody have a similar issue, and a possible solution?

Thanks!

**Comment by weaverryan** [comment]
Hmm. This is from a complex workaround in https://github.com/symfony/stimulus-bridge/blob/4204b399dfca85f209af38f3f5184fadcf4bbd23/src/webpack/loader.ts#L31-L39 ... a workaround we also use in Encore, and I can't find any issues there about it.

Does the error go away if you disable the vue loader?

**Comment by jmariller** [comment]
Hi @weaverryan, thanks a lot for getting back to me!

> Does the error go away if you disable the vue loader?

Not completely sure what you mean with *disable*, I take it you imply removing it from package.json. If so, here is the result when trying to compile:
![image](https://user-images.githubusercontent.com/48550159/173835307-2277645b-339c-4616-8550-03c18fcc36b7.png)

**Comment by jmariller** [comment]
Hi @weaverryan 

After further investigation and trying with a fresh project I noticed that the problem seems to be related to Yarn: when installing & compiling with NPM it works fine. Do you have any idea why?

**Comment by jmariller** [comment]
This is resolved thanks to Webpack 4.0 :) Thank you!

https://github.com/symfony/webpack-encore/releases/tag/v4.0.0
