### ISSUE TITLE
Error detected by eslint

### ISSUE THREAD

**Issue by garak** [symfony/stimulus-bridge#78]
I apologize in advance if I'm writing something stupid: I'm not really a Javascript expert.
I'm using this bridge and I created the following file, according to the documentation:

```js
import { startStimulusApp } from '@symfony/stimulus-bridge';

// Registers Stimulus controllers from controllers.json and in the controllers/ directory
export const app = startStimulusApp(require.context(
    '@symfony/stimulus-bridge/lazy-controller-loader!./controllers',
    true,
    /\.(j|t)sx?$/
));
```

The code is working and my Symfony application has no issues on this side.
The only problem is that when I run `DEBUG=eslint:cli-engine eslint ./assets/js` I get this error:

```
/user/app/assets/js/bootstrap.js
  4:37  error  'require' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```

Is there something I can do to fix it (or even workaround it)?

Versions of my packages:
"@hotwired/stimulus": "^3.2.1",
"eslint": "^8.32.0",

**Comment by weaverryan** [comment]
Hey!

Not a stupid question at all - I admit that this stuff still confuses me too :p.

The short answer, I believe, is to have eslint ignore this. `require.context` is a Webpack-specific feature... and I don't believe there is a way to replicate this using normal `import` statements. So, yea, it's an unfortunate "ugly" thing. Stimulus' docs itself also show this: https://stimulus.hotwired.dev/handbook/installing#using-webpack-helpers

Cheers!

**Comment by garak** [comment]
Thank you Ryan.
I leave here the configuration I used as a workaround, maybe it can be helpful for someone else. The relevant part is in the "overrides" key, and the "files" key should be adapted to your actual path.

```js
// .eslintrc.js
module.exports = {
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "rules": {
    },
    "overrides": [
        {
            "files": ["assets/js/bootstrap.js"],
            "rules": {
                "no-undef": ["off"]
            }
        }
    ]
};

``
