### ISSUE TITLE
 "@symfony/stimulus-bundle" module not found

### ISSUE THREAD

**Issue by koredalin** [symfony/stimulus-bridge#88]
Hello, Symfony Team,
I'm trying to install webpack on Symfony 7. I'm using these lessons tutorial "https://symfonycasts.com/screencast/symfony/webpack-encore-usage".
I tried also this tutorial: "https://symfonycasts.com/screencast/asset-mapper/stimulus" to instal Stimulus bundle.
The asset map looks pretty good to me but I still get an error: "Module build failed: Module not found:
"./assets/bootstrap.js" contains a reference to the file "@symfony/stimulus-bundle".
This file can not be found, please check it for typos or update it if the file got moved.".
I'm attaching you some pictures with the the issue and the code.
I've tried so many ways to resolve the issue but I still have no dicision.
Please, have a look and write me some fine answer back.

Thank you.
Best Regards.
Hristo Hristov

![image](https://github.com/symfony/stimulus-bridge/assets/6977867/1ed7c338-318b-4e2e-ac57-bcac462689a9)

![image](https://github.com/symfony/stimulus-bridge/assets/6977867/2c5da242-1df2-4a7e-996e-17bbc479c11f)

![image](https://github.com/symfony/stimulus-bridge/assets/6977867/1d076824-122a-4ac0-bae8-44d19fbd405d)

![image](https://github.com/symfony/stimulus-bridge/assets/6977867/0bfcc137-a0d3-4f9f-aa93-7399b8e0ea9e)

![image](https://github.com/symfony/stimulus-bridge/assets/6977867/95d52054-1921-412b-b8ee-34cb0a1b31e4)

**Comment by koredalin** [comment]
Ok,
I've read that I should install @symfony/stimulus-bridge first. I did it. Somehow the app was buided.
But now I have new error.
As you can see - the Bridge library is still not loaded right. I suppose that tha css files are loaded but the system tries to load them a second time in all.css file.
The files are loaded in "
http://127.0.0.1:8000/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_symfony_ux-turbo_dist-f44c0f.css" file. But the system tries to load them like "
http://127.0.0.1:8000/assets/styles/~@fortawesome/fontawesome-free/css/all.css".

I'm adding some pictures. So, you can understand what I'm doing.

![image](https://github.com/symfony/stimulus-bridge/assets/6977867/771f42f8-3923-4c38-9e35-acad51118c4d)

![image](https://github.com/symfony/stimulus-bridge/assets/6977867/e175d7c4-89de-4d66-a5f7-6890462376df)

![image](https://github.com/symfony/stimulus-bridge/assets/6977867/2aee03c9-c053-4493-97d9-38536689d18c)

![image](https://github.com/symfony/stimulus-bridge/assets/6977867/942bb422-3d91-456a-8e4c-462231597020)

![image](https://github.com/symfony/stimulus-bridge/assets/6977867/cef3d5d9-f4e2-464b-b17a-89e12bccb993)

I don't know what I can do more.
Please, help me.

Thank you.
Hristo Hristov

**Comment by David-Moisan** [comment]
Hi @koredalin, I have the same problem as you.

I searched the web and found this tip:

In your file assets/bootsrap.js : 
```javascript
import { startStimulusApp } from "@symfony/stimulus-bundle";
export const app = startStimulusApp();
```

Delete all "require.context" and change stimulus-bridge by **stimulus-bundle** 

Before compile your assets check if you have stimulus-bundle in importmap.php
And compile your asset mapper

**Comment by koredalin** [comment]
Thank you, @David-Moisan,
I have found that there is a typo in my code. Or sth like that. It was 2 months ago.
I have started symfonycasts.com tutorials from the same begining.
I don't remember what exactly was the issue.
However, I used the stimulus-bridge at the end.
If you are curious - you can review my code on:
https://github.com/koredalin/symfony-dent-calendar
or
https://github.com/koredalin/symfony-test-vinyl
One of these 2 repositories is fixed and working. :-)

Best Regards and Thank you, once again!

**Comment by kbond** [comment]
I think this issue can be closed but @koredalin, let me know if you want me to reopen.
